### ISSUE TITLE
Photo captions

### ISSUE THREAD

**Issue by caliholman** [caliholman/caliholman.github.io#11]
Is there a better way to add captions to the photos page?

I tried putting captions under two of them but they all just run together and it makes it hard to tell what is what. Is that something that can be formatted differently on your end?

**Comment by holmanb** [comment]
Yes, we can do something.  I'll put something together.

**Comment by holmanb** [comment]
I made some [changes](https://github.com/caliholman/caliholman.github.io/commit/c88d60d20729a7dd31145f80d892257e451c6dea) to the `/photos/photos.html` that I think might work.  Let me know what you think of it. If you are happy with what I have, feel free to close the comment.

If you had something different in mind, maybe find an example website and send me a link.
