### ISSUE TITLE
Add Pictures 

### ISSUE THREAD

**Issue by holmanb** [caliholman/caliholman.github.io#2]
Figure out which pics go where:

About
Tanzania
Photos
etc

**Comment by holmanb** [comment]
**Done:**
Photos: https://caliholman.github.io/photos/
About Me: https://caliholman.github.io/about/

**Todo:**
About Tanzania: https://caliholman.github.io/tanzania/

**Comment by holmanb** [comment]
I think that all that is left is an improvement to the first pic on `/tanzania`.
The purpose of this pic is to show where in Africa Tanzania is.

**Comment by holmanb** [comment]
@caliholman, can you find an appropriate picture and finish up this ticket please?

**Comment by caliholman** [comment]
Found new picture to show location of Tanzania and put it on the page
