### ISSUE TITLE
Explore Google Analytics

### ISSUE THREAD

**Issue by holmanb** [caliholman/caliholman.github.io#5]
https://chartio.com/learn/marketing-analytics/how-to-add-google-analytics-tracking-to-a-website/
https://stackoverflow.com/questions/17207458/how-to-add-google-analytics-tracking-id-to-github-pages

**Comment by holmanb** [comment]
https://desiredpersona.com/google-analytics-jekyll/

**Comment by caliholman** [comment]
Yes I want this.

**Comment by caliholman** [comment]
I completed this.
