### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by caliholman** [caliholman/caliholman.github.io#7]
On the different pages, the font size is large in relation to the different tabs at the top. It would be great if we could decrease the default size for all the text on the different pages to make it more uniform

**Comment by holmanb** [comment]
fyi - changes to `/css/main.css` will make formatting changes across the website 

 `font-size` (I think) defaults to `1.0em`.  the `<h1>` headers for example are set to `3em` (in markdown these are the lines that start with `#`)
