### ISSUE TITLE
Is an email okay?  Or do we prefer a contact us form instead?

### ISSUE THREAD

**Issue by holmanb** [caliholman/caliholman.github.io#8]
It would likely take a bunch of work, but it is possible to have a contact form instead of just a raw email.  Is it worth the effort? Or is the current state "good enough"?

https://medium.com/datafire-io/simple-backends-four-ways-to-implement-a-contact-us-form-on-a-static-website-10fc430984a4

**Comment by caliholman** [comment]
I think the simple email is good enough
